# Generated by Django 2.2.7 on 2019-11-09 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoItem',
            new_name='Item',
        ),
    ]
