# Generated by Django 2.2.7 on 2019-11-10 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_auto_20191109_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='todoApp.User'),
            preserve_default=False,
        ),
    ]
