# Generated by Django 2.2.7 on 2019-11-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoApp", "0003_auto_20191115_0316"),
    ]

    operations = [
        migrations.RemoveField(model_name="item", name="completed_date",),
        migrations.RemoveField(model_name="item", name="date_created",),
    ]
