# Generated by Django 2.2.7 on 2019-11-10 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("todoApp", "0003_item_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="item", name="user",),
        migrations.AddField(
            model_name="user",
            name="todo_list",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="todoApp.Item",
            ),
            preserve_default=False,
        ),
    ]
