# Generated by Django 2.2.7 on 2019-11-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoApp", "0004_auto_20191115_1207"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="completed_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="date_created",
            field=models.DateTimeField(default="2019-11-15"),
            preserve_default=False,
        ),
    ]
