# Generated by Django 2.2.7 on 2019-11-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoApp", "0005_auto_20191115_1226"),
    ]

    operations = [
        migrations.AddField(
            model_name="item", name="deadline", field=models.DateTimeField(null=True),
        ),
    ]
